// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC___XxU1Fh-9rVA9PRLwJC4EdT0_xWnqI',
    appId: '1:10697205840:web:bef6946dc1eaf1e0388955',
    messagingSenderId: '10697205840',
    projectId: 'tdcapp-daa22',
    authDomain: 'tdcapp-daa22.firebaseapp.com',
    storageBucket: 'tdcapp-daa22.appspot.com',
    measurementId: 'G-3STL8J6Z8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi_TpCLqtfpj1BF1DxdZRHEolfiyHmQdw',
    appId: '1:10697205840:android:78eccf2ac2e81537388955',
    messagingSenderId: '10697205840',
    projectId: 'tdcapp-daa22',
    storageBucket: 'tdcapp-daa22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqXOh0KsY7ZzgbZHlaE8YxcFaGD2DJ7HY',
    appId: '1:10697205840:ios:44136d40d03ca6a2388955',
    messagingSenderId: '10697205840',
    projectId: 'tdcapp-daa22',
    storageBucket: 'tdcapp-daa22.appspot.com',
    iosBundleId: 'com.example.tdc',
  );
}
